import { useEffect, useState } from "react";
import { api, inr } from "../api";

export default function Approvals({ tick }) {
  const [rows, setRows] = useState([]); const [processing, setProcessing] = useState(null); const [message, setMessage] = useState(null); const [error, setError] = useState(false);
  async function refresh() { setRows(await api.approvals()); }
  useEffect(() => { refresh().catch(() => setError(true)); }, [tick]);
  async function decide(id, type) { setProcessing(id); setMessage(null); try { await (type === "approve" ? api.approve(id) : api.reject(id)); setMessage(type === "approve" ? "Approval granted. The recovery action is executing." : "Recovery action rejected."); await refresh(); } catch (e) { setMessage(String(e).includes("409") ? "This approval was already processed." : "Unable to process this approval."); } finally { setProcessing(null); } }
  return <div className="space-y-6"><div><div className="page-eyebrow">Human in the loop</div><h1 className="page-title mt-2">Human approval required</h1><p className="text-sm text-slate-400 mt-2">{rows.length} action{rows.length === 1 ? "" : "s"} require your attention.</p></div>
    {message && <div className="panel px-4 py-3 text-sm text-violet-200 border-violet-500/30">{message}</div>}
    {error ? <div className="panel p-8 text-center text-rose-300">Unable to load approval queue. <button className="underline ml-2" onClick={() => { setError(false); refresh().catch(() => setError(true)); }}>Retry</button></div> : rows.length === 0 ? <div className="panel p-12 text-center"><div className="text-3xl mb-3">✓</div><div className="font-semibold">No approvals required</div><p className="text-sm text-slate-500 mt-2">ReSpark has no high-risk recovery actions waiting for you.</p></div> : <div className="grid md:grid-cols-2 gap-4">{rows.map((a) => <article key={a.id} className="panel p-5 border-l-2 border-l-amber-400"><div className="flex items-start justify-between gap-3"><div><div className="text-2xl font-extrabold">{inr(a.amount)}</div><div className="text-sm text-slate-400 mt-1">{a.customer_ref || "B2B customer"}</div></div><span className="status-pill status-warning">Pending</span></div><div className="grid grid-cols-2 gap-4 mt-6"><div><div className="text-[10px] uppercase tracking-widest text-slate-500">Recommended action</div><div className="text-sm font-semibold text-violet-300 mt-1">{a.action_type}</div></div><div><div className="text-[10px] uppercase tracking-widest text-slate-500">Risk</div><div className="text-sm mt-1">{a.risk || "High value"}</div></div></div><div className="mt-5 rounded-lg bg-amber-500/10 border border-amber-500/20 p-3"><div className="text-[10px] uppercase tracking-widest text-amber-300">Why?</div><div className="text-sm text-slate-300 mt-1">{a.reason}</div></div><div className="mt-5 space-y-2 text-xs text-slate-400"><div className="text-emerald-300">✓ Customer verified</div><div className="text-emerald-300">✓ Within contact policy</div><div className="text-amber-300">⚠ High-value transaction</div></div><div className="flex gap-2 mt-6"><button disabled={processing === a.id} onClick={() => decide(a.id, "approve")} className="flex-1 rounded-lg bg-emerald-400 py-2.5 text-sm font-bold text-slate-950 disabled:opacity-50">{processing === a.id ? "Processing…" : "Approve"}</button><button disabled={processing === a.id} onClick={() => decide(a.id, "reject")} className="flex-1 rounded-lg border border-rose-500/40 py-2.5 text-sm font-bold text-rose-300 disabled:opacity-50">Reject</button></div></article>)}</div>}
  </div>;
}
