import { useEffect, useState } from "react";
import { api, inr } from "../api";

const STATUS = { RECOVERED: "status-success", APPROVAL_REQUIRED: "status-warning", ESCALATED: "status-danger", EXECUTED: "status-info", CLOSED_LOST: "status-muted", DETECTED: "status-muted", DIAGNOSED: "status-info" };
const pretty = (value = "") => value.replaceAll("_", " ").toLowerCase().replace(/\b\w/g, (c) => c.toUpperCase());

function Detail({ id, onClose }) {
  const [detail, setDetail] = useState(null);
  useEffect(() => { api.recovery(id).then(setDetail).catch(() => setDetail({ error: true })); }, [id]);
  return <div className="fixed inset-0 z-50 bg-black/70 flex justify-end" onClick={onClose}><div className="h-full w-full max-w-2xl overflow-auto bg-[#0d131e] border-l border-[#263248]" onClick={(e) => e.stopPropagation()}>
    <div className="sticky top-0 z-10 flex justify-between items-center px-6 py-5 border-b border-[#202b3d] bg-[#0d131e]/95 backdrop-blur"><div><div className="page-eyebrow">Recovery detail</div><h2 className="text-lg font-bold mt-1">{id}</h2></div><button onClick={onClose} className="text-slate-500 hover:text-white text-xl">×</button></div>
    {!detail ? <div className="p-6 space-y-3"><div className="h-16 skeleton" /><div className="h-32 skeleton" /></div> : detail.error ? <div className="p-6 text-rose-300">Unable to load this recovery.</div> : <div className="p-6 space-y-5">
      <section className="panel p-5"><div className="flex justify-between gap-3"><div><div className="text-xs uppercase tracking-widest text-slate-500">Payment</div><div className="text-3xl font-extrabold mt-2">{inr(detail.payment.amount)}</div></div><span className={`status-pill ${STATUS[detail.status] || "status-muted"}`}>{pretty(detail.status)}</span></div><div className="grid grid-cols-2 gap-4 mt-5 text-xs"><div><span className="text-slate-500">Payment ID</span><div className="mono mt-1">{detail.payment.payment_id}</div></div><div><span className="text-slate-500">Order ID</span><div className="mono mt-1">{detail.payment.order_id || "—"}</div></div><div><span className="text-slate-500">Customer</span><div className="mt-1">{detail.payment.customer_ref || "—"}</div></div><div><span className="text-slate-500">Currency</span><div className="mt-1">{detail.payment.currency}</div></div></div></section>
      <section className="panel p-5"><div className="text-xs uppercase tracking-widest text-slate-500">Why did it fail?</div><div className="text-lg font-bold mt-2">{pretty(detail.root_cause || detail.payment.failure_reason || "Unknown reason")}</div><div className="mt-4 rounded-lg bg-violet-500/10 border border-violet-500/20 p-4"><div className="text-[11px] text-violet-300 uppercase tracking-widest">Agent diagnosis</div><div className="mt-2 text-sm">{detail.diagnosis || "Diagnosis recorded by the recovery agent."}</div></div></section>
      <section className="panel p-5"><div className="text-xs uppercase tracking-widest text-slate-500">Agent decision</div><div className="text-xl font-bold mt-2 text-violet-300">{pretty(detail.decision || "Pending")}</div><p className="text-sm text-slate-400 mt-2">Selected from the configured recovery strategies based on the payment diagnosis.</p></section>
      <section className="panel p-5 border-l-2 border-l-emerald-400"><div className="text-xs uppercase tracking-widest text-slate-500">Safety check</div><div className="space-y-3 mt-4 text-sm"><div className="text-emerald-300">✓ Customer and payment identified</div><div className="text-emerald-300">✓ Contact policy evaluated</div><div className="text-emerald-300">✓ Action is idempotent</div></div><div className="mt-5 pt-4 border-t border-slate-800 text-sm font-bold text-emerald-300">✓ {detail.status === "APPROVAL_REQUIRED" ? "HUMAN APPROVAL REQUIRED" : "ACTION ALLOWED"}</div></section>
      <section className="panel p-5"><div className="text-xs uppercase tracking-widest text-slate-500 mb-4">Recovery action timeline</div><div className="space-y-0">{detail.audit_timeline.map((event, index) => <div className="flex gap-4 relative pb-5 last:pb-0" key={`${event.created_at}-${index}`}><div className="flex flex-col items-center"><span className={`h-3 w-3 rounded-full ${index === detail.audit_timeline.length - 1 ? "bg-emerald-400" : "bg-violet-400"} ring-4 ring-[#101622] z-10`} />{index < detail.audit_timeline.length - 1 && <span className="w-px h-full bg-slate-700 absolute top-3" />}</div><div className="min-w-0"><div className="text-sm font-semibold">{pretty(event.action)}</div><div className="text-xs text-slate-500 mt-1">{event.created_at} · {event.actor}</div><div className="text-xs text-slate-400 mt-1">{event.rationale || "Event recorded by ReclaimAI."}</div></div></div>)}{detail.audit_timeline.length === 0 && <div className="text-sm text-slate-500">No audit events recorded yet.</div>}</div></section>
    </div>}
  </div></div>;
}

export default function Recoveries({ tick }) {
  const [rows, setRows] = useState([]); const [selected, setSelected] = useState(null); const [status, setStatus] = useState(""); const [search, setSearch] = useState(""); const [error, setError] = useState(false);
  useEffect(() => { api.recoveries(status ? `?status=${status}&limit=200` : "?limit=200").then(setRows).catch(() => setError(true)); }, [tick, status]);
  const visible = rows.filter((r) => `${r.payment_id} ${r.order_id} ${r.customer_ref}`.toLowerCase().includes(search.toLowerCase()));
  return <div className="space-y-6"><div className="flex flex-wrap justify-between gap-4 items-end"><div><div className="page-eyebrow">Operations</div><h1 className="page-title mt-2">Recoveries</h1><p className="text-sm text-slate-400 mt-2">Every failed payment, diagnosis, and recovery outcome in one place.</p></div><div className="text-xs text-slate-500">{rows.length} cases</div></div>
    <div className="panel p-4 flex flex-wrap gap-3"><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search customer, payment or order ID" className="flex-1 min-w-[220px] bg-[#0b1019] border border-[#29364b] rounded-lg px-3 py-2 text-sm outline-none focus:border-violet-400" /><select value={status} onChange={(e) => setStatus(e.target.value)} className="bg-[#0b1019] border border-[#29364b] rounded-lg px-3 py-2 text-sm text-slate-300"><option value="">All statuses</option>{Object.keys(STATUS).map((s) => <option key={s}>{s}</option>)}</select></div>
    {error ? <div className="panel p-8 text-center text-rose-300">Unable to load recoveries. <button className="underline ml-2" onClick={() => { setError(false); api.recoveries().then(setRows).catch(() => setError(true)); }}>Retry</button></div> : <div className="panel overflow-hidden"><div className="overflow-x-auto"><table className="w-full text-sm min-w-[850px]"><thead className="text-[10px] uppercase tracking-widest text-slate-500 bg-[#0c121d]"><tr>{["Status","Customer","Amount","Failure reason","Diagnosis","Selected action","Outcome"].map((h) => <th className="text-left px-4 py-3 font-bold" key={h}>{h}</th>)}</tr></thead><tbody>{visible.map((r) => <tr key={r.id} onClick={() => setSelected(r.id)} className="border-t border-slate-800/80 hover:bg-slate-800/30 cursor-pointer"><td className="px-4 py-4"><span className={`status-pill ${STATUS[r.status] || "status-muted"}`}>{pretty(r.status)}</span></td><td className="px-4 py-4"><div className="font-medium">{r.customer_ref || "Unknown customer"}</div><div className="mono text-[10px] text-slate-600 mt-1">{r.payment_id}</div></td><td className="px-4 py-4 font-semibold">{inr(r.amount)}</td><td className="px-4 py-4 text-slate-400">{pretty(r.failure_reason) || "—"}</td><td className="px-4 py-4 text-slate-400">{pretty(r.diagnosis || r.root_cause) || "Pending"}</td><td className="px-4 py-4 text-violet-300">{pretty(r.selected_action) || "Pending"}</td><td className="px-4 py-4 text-emerald-300">{r.recovered_amount > 0 ? inr(r.recovered_amount) : "—"}</td></tr>)}{visible.length === 0 && <tr><td colSpan="7" className="px-4 py-14 text-center"><div className="text-slate-300 font-semibold">No recoveries found</div><div className="text-sm text-slate-500 mt-2">Try adjusting your filters or run a simulation from the dashboard.</div></td></tr>}</tbody></table></div></div>}
    {selected && <Detail id={selected} onClose={() => setSelected(null)} />}
  </div>;
}
